Repository Gongkademy/Gongkademy_Front, pull requests merged in 2024-06, with the labels that each got.

#2 feat: PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ✨Feat

#7 [Refactor] 6 refactor router 리팩토링
  public/svg/logo/gongkademyText.svg
  public/svg/logo/logoImage.svg
  public/svg/logo/logoText.svg
  src/App.jsx
  src/assets/svg/logo/GongkademyText.tsx
  src/assets/svg/logo/LogoImage.tsx
  src/assets/svg/logo/LogoText.tsx
  src/assets/svg/logo/index.ts
  src/components/common/logo/Logo.jsx
  src/components/common/logo/Logo.style.js
  src/components/header/Header.jsx
  src/components/login/LoginModal.jsx
  src/index.jsx
  src/pages/CommunityArticle/CommunityArticlePage.jsx
  src/pages/CommunityBoard/CommunityBoardPage.jsx
  src/pages/CourseDetail/CourseCurriculum.jsx
  src/pages/CourseDetail/CourseDetailPage.jsx
  src/pages/CourseDetail/CourseIntroduction.jsx
  src/pages/CourseDetail/CourseNotice.jsx
  src/pages/CourseDetail/CourseQnA.jsx
  src/pages/CourseDetail/CourseReview.jsx
  src/pages/Home/HomePage.jsx
  src/pages/LecturePlayer/LecturePlayerPage.jsx
  src/pages/NotFound/NotFoundPage.jsx
  src/router/AppRouter.jsx
  src/router/Constants.js
  src/router/PrivateRoutes.jsx
Labels: ✨Feat, ♻️Refactor

#11 [FEAT] 버튼 컴포넌트 구현
  src/components/common/button/Button.jsx
  src/components/common/button/Button.style.js
  src/components/common/button/Button.style.jsx
  src/components/header/Header.jsx
  src/index.css
  src/styles/palette.js
Labels: ✨Feat, ♻️Refactor

#12 [FEAT] 강의 상세페이지 상단 css 작업
  public/svg/icons/BookIcon.svg
  public/svg/icons/BookMarkIcon.svg
  public/svg/icons/StarIcon.svg
  src/assets/svg/icons/BookIcon.tsx
  src/assets/svg/icons/BookMarkIcon.tsx
  src/assets/svg/icons/StarIcon.tsx
  src/assets/svg/icons/index.ts
  src/components/common/button/Button.jsx
  src/components/common/button/Button.style.js
  src/components/common/input/AuthNumInputGroup.jsx
  src/components/common/input/NormalInputGroup.jsx
  src/components/common/page/Page.style.js
  src/components/common/page/PageLayout.jsx
  src/components/common/text/Text.jsx
  src/components/courseDetail/courseDetailTop/CourseDetailTop.jsx
  src/components/courseDetail/courseDetailTop/CourseDetailTop.style.js
  src/components/courseDetail/courseMenu/CourseMenu.jsx
  src/components/courseDetail/courseMenu/CourseMenu.style.js
  src/components/courseDetail/courseSummary/CourseSummary.jsx
  src/components/courseDetail/courseSummary/CourseSummary.style.js
  src/components/courseDetail/courseThumbnail/CourseThumbnail.jsx
  src/components/courseDetail/courseThumbnail/CourseThumbnail.style.js
  src/components/header/Header.jsx
  src/components/header/Header.style.js
  src/components/lecture/lectureFooter/LectureFooter.jsx
  src/components/lecture/lectureHeader/LectureHeader.jsx
  src/components/lecture/lecturePlayer/LecturePlayer.jsx
  src/components/lecture/lecturePlayer/LecturePlayer.style.js
  src/components/lecture/lectureSideBar/LectureSidebar.style.js
  src/components/login/LoginModal.jsx
  src/components/signup/SignUpForm.jsx
  src/pages/CourseDetail/CourseDetailPage.jsx
  src/pages/Home/HomePage.jsx
  src/pages/Lecture/LecturePage.jsx
  src/pages/Lecture/LecturePage.style.js
  src/pages/MyPage/MyPage.jsx
  src/pages/Signup/SignUpPage.jsx
  src/router/AppRouter.jsx
  src/styles/palette.js
Labels: ✨Feat

#18 17 feat 커뮤니티 페이지 라우터 설정 및 css작업
  public/svg/icons/Bookmark-fill.svg
  src/assets/svg/icons/BookMarkFill.tsx
  src/assets/svg/icons/index.ts
  src/components/header/Header.jsx
  src/pages/Community/CommunityPage.jsx
  src/pages/Community/NavBar.jsx
  src/pages/CommunityBoard/Card/ConcernCard.jsx
  src/pages/CommunityBoard/Card/ConcernCard.style.js
  src/pages/CommunityBoard/Card/NoticeCard.jsx
  src/pages/CommunityBoard/Card/NoticeCard.style.js
  src/pages/CommunityBoard/Card/QnaCard.jsx
  src/pages/CommunityBoard/Card/QnaCard.style.js
  src/pages/CommunityBoard/CommunityBoardPage.jsx
  src/pages/CommunityBoard/Regist/Regist.jsx
  src/pages/CommunityBoard/Regist/Regist.style.js
  src/pages/CommunityBoard/Regist/ToastConcern.jsx
  src/pages/CommunityBoard/Regist/ToastQna.jsx
  src/pages/CommunityDetail/CommunityDetail.jsx
  src/pages/CommunityDetail/CommunityReview.jsx
  src/pages/CommunityDetail/CommunityReview.style.js
  src/pages/Home/HomePage.jsx
  src/router/AppRouter.jsx
  src/router/Constants.js
Labels: ✨Feat

#20 [Feat] toast UI 에디터 연결
  package-lock.json
  package.json
  src/components/common/editor/ToastUIEditor.jsx
  src/pages/Community/CommunityPage.jsx
  src/pages/Community/NavBar.jsx
  src/pages/CourseDetail/CourseDetailPage.jsx
  src/pages/Home/HomePage.jsx
  src/styles/editor.css
Labels: ✨Feat

#22 Refactor: svg 파일 컨벤션에 맞게 리팩토링
  public/svg/icons/ArrowLeftIcon.svg
  public/svg/icons/ArrowRightIcon.svg
  public/svg/icons/Bookmark-fill.svg
  public/svg/icons/Bookmark.svg
  public/svg/icons/CancelIcon.svg
  public/svg/icons/ChatIcon.svg
  public/svg/icons/CheckIcon.svg
  public/svg/icons/ChevronDownIcon.svg
  public/svg/icons/ChevronLeftIcon.svg
  public/svg/icons/ChevronRightIcon.svg
  public/svg/icons/ChevronUpIcon.svg
  public/svg/icons/InvisibleIcon.svg
  public/svg/icons/LikeActive.svg
  public/svg/icons/LikeIcon.svg
  public/svg/icons/MagnifierIcon.svg
  public/svg/icons/TrashCanIcon.svg
  public/svg/icons/TrophyIcon.svg
  public/svg/icons/VisibleIcon.svg
  src/assets/svg/icons/ArrowLeftIcon.tsx
  src/assets/svg/icons/ArrowRightIcon.tsx
  src/assets/svg/icons/BookMark.tsx
  src/assets/svg/icons/BookMarkFill.tsx
  src/assets/svg/icons/CancelIcon.tsx
  src/assets/svg/icons/ChatIcon.tsx
  src/assets/svg/icons/CheckIcon.tsx
  src/assets/svg/icons/ChevronDownIcon.tsx
  src/assets/svg/icons/ChevronLeftIcon.tsx
  src/assets/svg/icons/ChevronRightIcon.tsx
  src/assets/svg/icons/ChevronUpIcon.tsx
  src/assets/svg/icons/InvisibleIcon.tsx
  src/assets/svg/icons/LikeIcon.tsx
  src/assets/svg/icons/MagnifierIcon.tsx
  src/assets/svg/icons/TrashCanIcon.tsx
  src/assets/svg/icons/TrophyIcon.tsx
  src/assets/svg/icons/VisibleIcon.tsx
  src/assets/svg/icons/index.ts
  src/components/common/input/PwdInputGroup.jsx
  src/components/common/searchbar/SearchBar.jsx
  src/components/lecture/lectureFooter/LectureFooter.jsx
  src/components/lecture/lectureHeader/LectureHeader.jsx
  src/components/login/LoginModal.jsx
  src/pages/CommunityBoard/Card/ConcernCard.jsx
  src/pages/CommunityBoard/Card/NoticeCard.jsx
  src/pages/CommunityBoard/Card/QnaCard.jsx
  src/pages/CommunityBoard/Regist/Regist.jsx
Labels: ♻️Refactor

#23 Revert: QnA 페이지의 VisibleIcon에러 수정후 다시 PR ("Refactor: svg 파일 컨벤션에 맞게 리팩토링")
  public/svg/icons/Arrow-left.svg
  public/svg/icons/Arrow-right.svg
  public/svg/icons/Bookmark-fill.svg
  public/svg/icons/Bookmark.svg
  public/svg/icons/Cancel.svg
  public/svg/icons/Check.svg
  public/svg/icons/Chevron-Down.svg
  public/svg/icons/Chevron-Up.svg
  public/svg/icons/Chevron-left.svg
  public/svg/icons/Chevron-right.svg
  public/svg/icons/Invisible.svg
  public/svg/icons/LikeActive.svg
  public/svg/icons/LikeIcon.svg
  public/svg/icons/Magnifier.svg
  public/svg/icons/Visible.svg
  public/svg/icons/chat.svg
  public/svg/icons/trash can.svg
  public/svg/icons/trophy.svg
  src/assets/svg/icons/ArrowLeft.tsx
  src/assets/svg/icons/ArrowLeftIcon.tsx
  src/assets/svg/icons/ArrowRight.tsx
  src/assets/svg/icons/ArrowRightIcon.tsx
  src/assets/svg/icons/BookMark.tsx
  src/assets/svg/icons/BookMarkFill.tsx
  src/assets/svg/icons/ChatIcon.tsx
  src/assets/svg/icons/ChevronDown.tsx
  src/assets/svg/icons/ChevronLeft.tsx
  src/assets/svg/icons/ChevronLeftIcon.tsx
  src/assets/svg/icons/ChevronRight.tsx
  src/assets/svg/icons/ChevronUp.tsx
  src/assets/svg/icons/InvisibleIcon.tsx
  src/assets/svg/icons/LikeIcon.tsx
  src/assets/svg/icons/MagnifierIcon.tsx
  src/assets/svg/icons/TrophyIcon.tsx
  src/assets/svg/icons/VisibleIcon.tsx
  src/assets/svg/icons/index.ts
  src/components/common/input/PwdInputGroup.jsx
  src/components/common/searchbar/SearchBar.jsx
  src/components/lecture/lectureFooter/LectureFooter.jsx
  src/components/lecture/lectureHeader/LectureHeader.jsx
  src/components/login/LoginModal.jsx
  src/pages/CommunityBoard/Card/ConcernCard.jsx
  src/pages/CommunityBoard/Card/NoticeCard.jsx
  src/pages/CommunityBoard/Card/QnaCard.jsx
  src/pages/CommunityBoard/Regist/Regist.jsx
Labels: 🐛Fix

#26 Refactor: QnA페이지에서 viibleIcon 수정
  src/pages/CommunityBoard/Card/QnaCard.jsx
Labels: ♻️Refactor

#28 Refactor: 필요없는 Svg 컴포넌트 삭제
  src/assets/svg/icons/Cancel.tsx
  src/assets/svg/icons/Chat.tsx
  src/assets/svg/icons/Check.tsx
  src/assets/svg/icons/Invisible.tsx
  src/assets/svg/icons/Like.tsx
  src/assets/svg/icons/LikeActive.tsx
  src/assets/svg/icons/Magnifier.tsx
  src/assets/svg/icons/TrashCan.tsx
  src/assets/svg/icons/Trophy.tsx
  src/assets/svg/icons/Visible.tsx
Labels: ♻️Refactor

#29 [FEAT] 강의 상세페이지 강의목차 css 작업
  public/svg/icons/CheckIcon.svg
  src/App.jsx
  src/assets/svg/icons/CheckIcon.tsx
  src/components/common/page/Page.style.js
  src/components/common/text/Text.style.js
  src/components/courseDetail/courseCurriculum/CourseCurriculum.jsx
  src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
  src/components/courseDetail/courseCurriculum/CurriculumItem.style.js
  src/components/courseDetail/courseIntroduction/CourseIntroduction.jsx
  src/components/courseDetail/courseMenu/CourseMenu.style.js
  src/components/courseDetail/courseNotice/CourseNotice.jsx
  src/components/courseDetail/courseQnA/CourseQnA.jsx
  src/components/courseDetail/courseReview/CourseReview.jsx
  src/components/lecture/lectureFooter/LectureFooter.jsx
  src/components/lecture/lecturePlayer/LecturePlayer.jsx
  src/index.css
  src/pages/CourseDetail/CourseCurriculum.jsx
  src/pages/CourseDetail/CourseDetailPage.jsx
  src/router/AppRouter.jsx
  src/styles/theme.js
Labels: ✨Feat, ♻️Refactor

#34 Refactor: Select폴더 분리
  src/components/common/searchbar/SearchBar.jsx
  src/components/common/searchbar/Select.jsx
Labels: ♻️Refactor

#36 Refactor: Select너비 props설정으로 변경
  src/components/common/searchbar/SearchBar.jsx
  src/components/common/searchbar/Searchbar.style.js
  src/components/common/searchbar/Select.jsx
Labels: ♻️Refactor

#38 FEAT: 고민&질문 글 등록 페이지+리뷰 등록
  src/components/common/searchbar/Searchbar.style.js
  src/components/common/searchbar/Select.jsx
  src/pages/CommunityBoard/Regist/Regist.jsx
  src/pages/CommunityBoard/Regist/Regist.style.js
  src/pages/CommunityBoard/Regist/RegistCourse.jsx
  src/pages/CommunityBoard/Regist/RegistNav.jsx
  src/pages/CommunityBoard/Regist/RegistReview.jsx
  src/pages/CommunityBoard/Regist/ToastConcern.jsx
  src/pages/CommunityBoard/Regist/ToastQna.jsx
  src/pages/CommunityDetail/CommunityDetail.jsx
  src/pages/CommunityDetail/CommunityReview.jsx
Labels: ✨Feat

#40 FEAT: community api 추가
  src/apis/apiConstants.js
  src/apis/community/QnaApi.js
  src/apis/community/ReviewApi.js
  src/apis/community/concernApi.js
  src/apis/community/noticeApi.js
Labels: ✨Feat

#42 REFACTOR: 커뮤니티 컴포넌트&페이지 구조 변경
  src/components/community/Card/ConcernCard.jsx
  src/components/community/Card/ConcernCard.style.js
  src/components/community/Card/NoticeCard.jsx
  src/components/community/Card/NoticeCard.style.js
  src/components/community/Card/QnaCard.jsx
  src/components/community/Card/QnaCard.style.js
  src/components/community/NavBar/NavBar.jsx
  src/components/community/NavBar/NavBar.style.js
  src/components/community/Regist/RegistCourse.jsx
  src/components/community/Regist/RegistNav.jsx
  src/components/community/Regist/RegistReview.jsx
  src/components/community/Regist/ToastConcern.jsx
  src/components/community/Regist/ToastQna.jsx
  src/components/community/Regist/communityRegist.style.js
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/pages/Community/CommunityPage.jsx
  src/pages/Community/CommunityPage.style.js
  src/pages/CommunityDetail/CommunityDetail.jsx
  src/pages/CommunityDetail/CommunityReview.jsx
  src/pages/CommunityRegist/CommunityRegistPage.jsx
  src/pages/CommunityRegist/CommunityRegistPage.style.js
  src/router/AppRouter.jsx
Labels: ♻️Refactor

#43 [FEAT] 강의 상세페이지 수강평 css 작업
  src/assets/svg/icons/LikeIcon.tsx
  src/assets/svg/icons/StarIcon.tsx
  src/components/common/button/Button.style.js
  src/components/common/rating/Rating.jsx
  src/components/common/rating/Rating.style.js
  src/components/common/review/Review.jsx
  src/components/common/review/Review.style.js
  src/components/common/searchbar/SearchBar.jsx
  src/components/common/searchbar/Searchbar.style.js
  src/components/common/searchbar/Select.jsx
  src/components/common/select/Select.jsx
  src/components/common/select/Select.style.js
  src/components/common/textarea/TextArea.jsx
  src/components/common/textarea/TextArea.style.js
  src/components/community/Card/NoticeCard.jsx
  src/components/community/Card/QnaCard.jsx
  src/components/community/Regist/RegistCourse.jsx
  src/components/community/Regist/RegistNav.jsx
  src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
  src/components/courseDetail/courseCurriculum/CurriculumItem.style.js
  src/components/courseDetail/courseDetailTop/CourseDetailTop.style.js
  src/components/courseDetail/courseMenu/CourseMenu.style.js
  src/components/courseDetail/courseReview/CourseReview.jsx
  src/components/courseDetail/courseSummary/CourseSummary.jsx
  src/components/courseDetail/courseThumbnail/CourseThumbnail.style.js
  src/dummy/Review.js
  src/index.css
  src/pages/CommunityDetail/CommunityDetail.jsx
  src/pages/CommunityDetail/CommunityReview.jsx
  src/pages/CommunityDetail/CommunitySubReview.jsx
  src/pages/CommunityRegist/CommunityRegistPage.jsx
  src/pages/CourseDetail/CourseDetailPage.jsx
  src/pages/MyPage/MyPageUpdate.style.jsx
  src/styles/palette.js
  src/styles/style.js
Labels: ✨Feat

#45 Refactor: CommunityPage& CommunityBoardPage 구조 변경
  .vscode/launch.json
  src/components/community/Card/CommunityCard.jsx
  src/components/community/Card/CommunityCard.style.js
  src/components/community/Card/ConcernCard.jsx
  src/components/community/Card/ConcernCard.style.js
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/dummy/Concern.js
  src/pages/Community/CommunityPage.jsx
  src/pages/Community/CommunityPage.style.js
Labels: ♻️Refactor

#47 FEAT: 상세페이지에서 수정페이지 이동 + 미트볼클릭시 버튼활성화
  src/components/common/select/MeetballSelect.jsx
  src/components/common/select/MeetballSelect.style.js
  src/pages/CommunityDetail/CommunityDetail.jsx
  src/pages/CommunityUpdate/CommunityUpdatePage.jsx
  src/router/AppRouter.jsx
  src/router/Constants.js
Labels: ✨Feat

#50 Feat: 커뮤니티 페이지 api연결 + 수정
  src/apis/axiosInstance.js
  src/apis/community/QnaApi.js
  src/apis/community/concernApi.js
  src/apis/community/noticeApi.js
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/stores/Community/ConcernStore.js
  src/stores/Community/NoticeStore.js
  src/stores/Community/QnaStore.js
  src/stores/Community/ReviewStore.js
Labels: ✨Feat, ♻️Refactor

#53 Refactor: 질문,고민 리스트 api파라미터 추가
  src/apis/community/QnaApi.js
  src/apis/community/concernApi.js
  src/components/common/pagination/pagination.jsx
  src/components/common/pagination/pagination.style.js
Labels: ♻️Refactor
