Repository Gongkademy/Gongkademy_Front, pull requests merged in 2024-07, with the labels that each got.

#54 FEAT: 페이지네이션 구현 + 커뮤니티url쿼리스트링 설정
  src/apis/apiConstants.js
  src/components/common/pagination/pagination.jsx
  src/components/common/pagination/pagination.style.js
  src/components/common/searchbar/SearchBar.jsx
  src/components/common/select/Select.jsx
  src/components/community/NavBar/NavBar.jsx
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/components/header/Header.jsx
  src/pages/Community/CommunityPage.jsx
  src/stores/Community/ConcernStore.js
  src/stores/Community/QnaStore.js
  src/stores/common/CommonStore.js
Labels: ✨Feat, ♻️Refactor

#55 FEAT 회원가입 구현디자인 수정 + api 연결
  public/svg/icons/checkboxIcon.svg
  public/svg/icons/meetballIcon.svg
  public/svg/logo/Google.svg
  src/apis/axiosInstance.js
  src/apis/members/membersApi.js
  src/assets/svg/icons/CheckboxIcon.tsx
  src/assets/svg/icons/index.ts
  src/assets/svg/logo/Google.tsx
  src/assets/svg/logo/index.ts
  src/components/common/checkbox/Checkbox.jsx
  src/components/common/checkbox/Checkbox.style.js
  src/components/common/input/AuthNumInputGroup.jsx
  src/components/common/input/Input.jsx
  src/components/common/input/Input.style.js
  src/components/common/input/InputGroup.jsx
  src/components/common/input/InputGroup.style.js
  src/components/common/input/NormalInputGroup.jsx
  src/components/common/input/PwdInputGroup.jsx
  src/components/common/input/ValidMessage.jsx
  src/components/common/page/Page.style.js
  src/components/common/page/PageTitle.jsx
  src/components/common/text/Text.jsx
  src/components/common/text/Text.style.js
  src/components/header/Header.jsx
  src/components/login/Constant.js
  src/components/login/LoginModal.jsx
  src/components/login/LoginModal.style.js
  src/components/login/Modal.style.js
  src/components/signup/Constants.js
  src/components/signup/SignUpForm.jsx
  src/components/signup/SignUpForm.style.js
  src/hooks/useForm.jsx
  src/index.css
  src/pages/CommunityDetail/CommunityDetail.jsx
  src/pages/Signup/SignUpPage.jsx
  src/utils/validate.js
Labels: ✨Feat, ♻️Refactor

#59 Refactor: 커뮤니티상세보기 & 리스트아이템(카드) 상태관리 수정(store사용) 및 변수명 변경
  src/components/community/Card/CommunityCard.jsx
  src/components/community/Card/NoticeCard.jsx
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/pages/CommunityDetail/CommunityDetail.jsx
Labels: ✨Feat, ♻️Refactor

#61 Refactor: 커뮤니티 api수정(community추가)
  src/apis/apiConstants.js
  src/components/community/Card/CommunityCard.jsx
  src/components/community/Card/NoticeCard.jsx
Labels: ♻️Refactor

#64 Refactor: 관리자 Repository의 코드를 서비스 Repository로 이동
  src/AdminApp.jsx
  src/components/admin/header/AdminHeader.jsx
  src/components/admin/navbar/AdminCommunityNavbar.Style.js
  src/components/admin/navbar/AdminCommunityNavbar.jsx
  src/components/admin/navbar/AdminLectureNavbar.Style.js
  src/components/admin/navbar/AdminLectureNavbar.jsx
  src/components/common/pagination/pagination.jsx
  src/components/common/review/Review.jsx
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
  src/components/lecture/lectureFooter/LectureFooter.jsx
  src/pages/Admin/CommunityConcern/AdminCommunityConcernPage.jsx
  src/pages/Admin/CommunityNotice/AdminCommunityNoticePage.jsx
  src/pages/Admin/CommunityQna/AdminCommunityQnaPage.jsx
  src/pages/Admin/Home/AdminHomePage.jsx
  src/pages/Admin/Lecture/AdminLecturePage.jsx
  src/pages/Admin/LectureCourseReview/AdminLectureCourseReviewPage.jsx
  src/pages/Admin/LectureIntro/AdminLectureIntroPage.jsx
  src/pages/Admin/LectureNotice/AdminLectureNoticePage.jsx
  src/pages/Admin/LectureOrder/AdminLectureOrderPage.jsx
  src/pages/Admin/LectureQna/AdminLectureQnaPage.jsx
  src/pages/Admin/LectureRegist/AdminLectureRegistPage.jsx
  src/pages/Admin/Member/AdminMemberPage.jsx
  src/pages/Service/Community/CommunityPage.jsx
  src/pages/Service/Community/CommunityPage.style.js
  src/pages/Service/CommunityDetail/CommunityDetail.jsx
  src/pages/Service/CommunityDetail/CommunityDetail.style.js
  src/pages/Service/CommunityRegist/CommunityRegistPage.jsx
  src/pages/Service/CommunityRegist/CommunityRegistPage.style.js
  src/pages/Service/CommunityUpdate/CommunityUpdatePage.jsx
  src/pages/Service/CourseDetail/CourseDetailPage.jsx
  src/pages/Service/Courses/CoursesPage.jsx
  src/pages/Service/Home/HomePage.jsx
  src/pages/Service/Lecture/LecturePage.jsx
  src/pages/Service/Lecture/LecturePage.style.js
  src/pages/Service/Lecture/constants.js
  src/pages/Service/MyPage/MyPage.jsx
  src/pages/Service/MyPage/MyPage.style.js
  src/pages/Service/MyPage/MyPageUpdate.jsx
  src/pages/Service/MyPage/MyPageUpdate.style.jsx
  src/pages/Service/Signup/SignUpPage.jsx
  src/router/AppRouter.jsx
  src/router/Constants.js
Labels: ♻️Refactor

#66 FIX: 페이지네이션 파일명 변경
  src/components/common/pagination/Pagination.jsx
  src/components/common/pagination/Pagination.style.js
Labels: 🐛Fix

#68 REFACTOR: pagination import코드 수정
  src/components/common/pagination/Pagination.jsx
  src/pages/Service/Community/CommunityPage.jsx
Labels: 🐛Fix, ♻️Refactor

#70 feat 게시물 등록 post요청
  src/apis/community/QnaApi.js
  src/apis/community/concernApi.js
  src/components/community/Regist/RegistCourse.jsx
  src/components/community/Regist/RegistNav.jsx
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/pages/Service/CommunityRegist/CommunityRegistPage.jsx
  src/stores/Community/ConcernStore.js
  src/stores/Community/QnaStore.js
Labels: ✨Feat, ♻️Refactor

#72 Feat: 강의,강좌 관리자 기능 API 설정
  src/apis/apiConstants.js
  src/apis/axiosInstance.js
  src/apis/course/adminCourseApi.js
Labels: ✨Feat

#73 Feat: 관리자 강의 등록 페이지 디자인+API 작업
  src/apis/apiConstants.js
  src/apis/course/adminCourseApi.js
  src/components/common/imageUpload/ImageUpload.jsx
  src/components/common/imageUpload/ImageUpload.style.js
  src/pages/Admin/Lecture/AdminLecturePage.jsx
  src/pages/Admin/LectureRegist/AdminLectureRegistPage.jsx
  src/router/AppRouter.jsx
Labels: ✨Feat

#75 Feat: 관리자 강좌 조회페이지 구현(디자인+api)
  src/apis/course/adminCourseApi.js
  src/components/admin/lecture/AdminLectureItem.jsx
  src/components/admin/navbar/AdminCourseNavbar.Style.js
  src/components/admin/navbar/AdminCourseNavbar.jsx
  src/pages/Admin/Course/AdminCoursePage.jsx
  src/pages/Admin/CourseIntro/AdminCourseIntroPage.jsx
  src/pages/Admin/CourseNotice/AdminCourseNoticePage.jsx
  src/pages/Admin/CourseOrder/AdminCourseOrderPage.jsx
  src/pages/Admin/CourseQna/AdminCourseQnaPage.jsx
  src/pages/Admin/CourseRegist/AdminCourseRegistPage.jsx
  src/pages/Admin/CourseReview/AdminCourseReviewPage.jsx
  src/pages/Admin/Lecture/AdminLecturePage.jsx
  src/pages/Admin/LectureCourseReview/AdminLectureCourseReviewPage.jsx
  src/pages/Admin/LectureIntro/AdminLectureIntroPage.jsx
  src/pages/Admin/LectureNotice/AdminLectureNoticePage.jsx
  src/pages/Admin/LectureOrder/AdminLectureOrderPage.jsx
  src/pages/Admin/LectureQna/AdminLectureQnaPage.jsx
  src/router/AppRouter.jsx
  src/router/Constants.js
Labels: ✨Feat

#78 Feat: 서비스 강의,강좌에 필요한 API 호출함수 작성
  src/apis/apiConstants.js
  src/apis/course/courseApi.js
  src/apis/course/courseCommentApi.js
  src/apis/course/courseReviewApi.js
  src/apis/course/playerApi.js
Labels: ✨Feat

#80 FIX: 커뮤니티 리스트 조회 에러 수정
  src/apis/community/QnaApi.js
  src/apis/community/ReviewApi.js
  src/apis/community/concernApi.js
  src/apis/community/noticeApi.js
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/stores/Community/ConcernStore.js
Labels: 🐛Fix, ♻️Refactor

#81 Feat: 관리자 강의 목차 페이지 구현 (디자인+api)
  src/apis/apiConstants.js
  src/apis/course/adminCourseApi.js
  src/apis/course/courseApi.js
  src/components/admin/navbar/AdminCourseNavbar.jsx
  src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
  src/hooks/useForm.jsx
  src/pages/Admin/CourseOrder/AdminCourseOrderPage.jsx
Labels: ✨Feat, ♻️Refactor

#85 Fix: vscode 자동완성 안되는 에러 해결
  jsconfig.json
  src/vite-env.d.ts
  tsconfig.json
  vite-env.d.ts
  vite.config.js
Labels: 🐛Fix

#87 Fix: path alias 설정이후 프론트 서버 안뜨는 문제
  jsconfig.json
  src/components/common/rating/Rating.jsx
  src/components/common/review/Review.jsx
  src/components/common/searchbar/SearchBar.jsx
  src/components/common/select/Select.jsx
  src/components/community/Card/CommunityCard.jsx
  src/components/community/Card/NoticeCard.jsx
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/components/course/CourseCard.jsx
  src/components/courseDetail/courseSummary/CourseSummary.jsx
  src/components/lecture/lectureFooter/LectureFooter.jsx
  src/pages/Admin/CourseOrder/AdminCourseOrderPage.jsx
  src/pages/Service/Community/CommunityPage.jsx
  src/pages/Service/CommunityDetail/CommunityDetail.jsx
  src/pages/Service/CommunityRegist/CommunityRegistPage.jsx
  src/pages/Service/Courses/CoursesPage.jsx
  src/stores/Community/ConcernStore.js
  src/stores/Community/NoticeStore.js
  src/stores/Community/QnaStore.js
  vite.config.js
Labels: 🐛Fix

#88 83 feat 홈,강의,강의 목차 플로우 완성
  public/svg/icons/teacherIcon.svg
  src/assets/svg/icons/TeacherIcon.tsx
  src/assets/svg/icons/index.ts
  src/components/common/page/Page.style.js
  src/components/common/page/PageTitle.jsx
  src/components/constants.js
  src/components/courseDetail/courseCurriculum/CourseCurriculum.jsx
  src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
  src/components/courseDetail/courseDetailTop/CourseDetailTop.jsx
  src/components/courseDetail/courseMenu/CourseMenu.jsx
  src/components/courseDetail/courseSummary/CourseSummary.jsx
  src/components/courseDetail/courseSummary/CourseSummary.style.js
  src/components/courseDetail/courseThumbnail/CourseThumbnail.jsx
  src/components/courseDetail/courseThumbnail/CourseThumbnail.style.js
  src/pages/Admin/CourseRegist/AdminCourseRegistPage.jsx
  src/pages/Service/Courses/CoursePage.style.js
  src/pages/Service/Courses/CoursesPage.jsx
  src/pages/Service/Home/HomePage.jsx
Labels: ✨Feat

#91 Feat: 강의플레이어 재생기능 구현
  package-lock.json
  package.json
  src/apis/apiConstants.js
  src/apis/course/courseApi.js
  src/apis/course/playerApi.js
  src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
  src/components/courseDetail/courseSummary/CourseSummary.jsx
  src/components/lecture/lectureFooter/LectureFooter.jsx
  src/components/lecture/lectureHeader/LectureHeader.jsx
  src/components/lecture/lecturePlayer/LecturePlayer.jsx
  src/pages/Service/Lecture/LecturePage.jsx
  src/pages/Service/Lecture/constants.js
  src/stores/course/lectureStore.js
Labels: ✨Feat

#96 REFACTOR : 커뮤니티 리스트 & 커뮤니티 상세보기 수정
  src/apis/community/QnaApi.js
  src/components/community/Card/CommunityCard.jsx
  src/components/community/Card/NoticeCard.jsx
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/pages/Service/Community/CommunityPage.jsx
  src/pages/Service/CommunityDetail/CommunityDetail.jsx
  src/pages/Service/CommunityRegist/CommunityRegistPage.jsx
  src/stores/Community/ConcernStore.js
  src/stores/Community/QnaStore.js
Labels: ✨Feat, ♻️Refactor

#98 FEAT : 커뮤니티 검색 및 페이지 이동 구현
  src/components/common/pagination/Pagination.jsx
  src/components/common/searchbar/SearchBar.jsx
  src/components/common/select/Select.jsx
  src/pages/Service/Community/CommunityPage.jsx
Labels: ✨Feat, ♻️Refactor

#101 FEAT: 로그인시 헤더 구현 + store에 저장
  src/apis/apiConstants.js
  src/apis/members/membersApi.js
  src/components/header/Header.jsx
  src/components/signup/SignUpForm.jsx
  src/pages/Service/GoogleRedirect/GoogleRedirectPage.jsx
  src/pages/Service/Home/HomePage.jsx
  src/router/AppRouter.jsx
  src/router/Constants.js
  src/stores/member/constant.js
  src/stores/member/loginStore.js
  src/stores/member/memberStore.js
Labels: ✨Feat

#105 102 feat 로그인 토큰 만료시 헤더 변경 구현
  src/apis/apiConstants.js
  src/apis/axiosInstance.js
  src/components/header/Header.jsx
  src/pages/Service/GoogleRedirect/GoogleRedirectPage.jsx
Labels: ✨Feat

#108 FEAT: 마이페이지 라우터 구현
  src/pages/Service/MemberDelete/MemberDeletePage.jsx
  src/pages/Service/MyCommunity/MyCommunityPage.jsx
  src/pages/Service/MyCourse/MyCoursePage.jsx
  src/pages/Service/MyInfoUpdate/MyInfoUpdatePage.jsx
  src/pages/Service/MyNotificationSetting/MyNotificationSettingPage.jsx
  src/pages/Service/MyPage/MyPage.jsx
  src/router/AppRouter.jsx
  src/router/Constants.js
Labels: ✨Feat

#110 Feat: protected router 구현
  src/apis/apiConstants.js
  src/apis/axiosInstance.js
  src/apis/members/membersApi.js
  src/pages/Service/Home/HomePage.jsx
  src/router/AppRouter.jsx
  src/router/PrivaterRouter.jsx
Labels: ✨Feat

#114 REFACTOR:커뮤니티 비로그인 로그인 구분 수정
  src/apis/community/QnaApi.js
  src/apis/community/concernApi.js
  src/apis/community/noticeApi.js
  src/components/community/Card/CommunityCard.jsx
  src/components/community/Card/NoticeCard.jsx
  src/components/community/communityBoard/CommunityBoardPage.jsx
  src/pages/Service/Community/CommunityPage.jsx
  src/pages/Service/CommunityDetail/CommunityDetail.jsx
  src/stores/Community/ConcernStore.js
  src/stores/Community/NoticeStore.js
  src/stores/Community/QnaStore.js
Labels: ✨Feat, ♻️Refactor

#116 REFACTOR:toastui지우고 react-quil설치
  package-lock.json
  package.json
Labels: ♻️Refactor

#117 REFACTOR: 커뮤니티 글 등록 및 상세페이지 수정 + Editor변경
  index.html
  package-lock.json
  package.json
  src/apis/apiConstants.js
  src/components/common/editor/QuillEditor.jsx
  src/components/common/editor/QuillEditor.style.js
  src/components/common/editor/QuillModule.jsx
  src/components/common/editor/ToastUIEditor.jsx
  src/components/common/modal/Alarm/Alarm.jsx
  src/components/common/modal/Alarm/Alarm.style.js
  src/components/common/searchbar/SearchBar.jsx
  src/components/common/select/Select.jsx
  src/components/community/Card/CommunityCard.jsx
  src/components/community/Regist/ConcernEditor.jsx
  src/components/community/Regist/QnaEditor.jsx
  src/components/community/Regist/RegistCourse.jsx
  src/components/community/Regist/RegistReview.jsx
  src/components/community/Regist/ToastConcern.jsx
  src/components/community/Regist/ToastQna.jsx
  src/index.jsx
  src/pages/Service/CommunityDetail/CommunityDetail.jsx
  src/pages/Service/CommunityDetail/CommunityDetail.style.js
  src/pages/Service/CommunityRegist/CommunityRegistPage.jsx
  src/stores/Community/ReviewStore.js
Labels: ✨Feat, ♻️Refactor

#118 Feat: 회원정보 수정 페이지 구현
  jsconfig.json
  package-lock.json
  package.json
  public/svg/icons/fileIcon.svg
  src/apis/members/membersApi.js
  src/assets/svg/icons/CheckIcon.tsx
  src/assets/svg/icons/FileIcon.tsx
  src/assets/svg/icons/index.ts
  src/components/common/flex/Flex.style.js
  src/components/common/input/Input.jsx
  src/components/common/profile/Profile.jsx
  src/components/common/profile/Profile.style.js
  src/components/courseDetail/courseCurriculum/CurriculumItem.jsx
  src/hooks/useForm.jsx
  src/hooks/useValidateInput.jsx
  src/hooks/useVisible.jsx
  src/index.jsx
  src/pages/Service/MyInfoUpdate/MyInfoUpdatePage.jsx
  src/pages/Service/MyPage/MyPageUpdate.jsx
  src/pages/Service/MyPage/MyPageUpdate.style.jsx
  src/queries/useMemberQuery.js
  src/utils/validate.js
  vite.config.js
Labels: ✨Feat, ♻️Refactor

#120 Feat: 마이페이지 회원탈퇴 구현
  src/apis/members/membersApi.js
  src/components/common/button/Button.style.js
  src/components/common/modal/confirmModal/ConfirmModal.jsx
  src/components/common/modal/confirmModal/ConfirmModal.style.js
  src/components/common/modal/confirmModal/MemberDeleteConfirmModal.jsx
  src/pages/Service/MyPage/MyPage.jsx
Labels: ✨Feat

#121 Feat: 강의 소개페이지 구현
  package-lock.json
  src/apis/apiConstants.js
  src/apis/common/imageApi.js
  src/apis/course/adminCourseApi.js
  src/components/admin/course/CourseIntroEditor.jsx
  src/components/common/editor/QuillEditor.style.js
  src/components/common/textarea/TextArea.jsx
  src/components/common/textbox/TextBox.jsx
  src/components/common/textbox/Textbox.style.js
  src/components/courseDetail/courseIntroduction/CourseIntroduction.jsx
  src/hooks/useForm.jsx
  src/pages/Admin/Course/AdminCoursePage.jsx
  src/pages/Admin/CourseIntro/AdminCourseIntroPage.jsx
  src/queries/useCourseDetailQuery.js
Labels: ✨Feat
